# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20161230_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_sector',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('FOOD_AND_DRINK', 'Food & Drink'), ('ENTERTAINMENT', 'Entertainment')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='confirmed_name',
            field=models.BooleanField(default=False),
        ),
    ]
