# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_phone_number_confirmation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_sector', models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('FOOD_AND_DRINK', 'Food & Drink'), ('ENTERTAINMENT', 'Entertainment')], max_length=100, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('address_line_1', models.CharField(max_length=200, null=True)),
                ('address_line_2', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('locality', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=9, null=True)),
                ('registered_company_number', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddressLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='business_sector',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registered_company_number',
        ),
    ]
