# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20170104_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAddressLine',
        ),
    ]
