# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_delete_companyaddressline'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
