# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20170105_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
